name: 01 Push Trigger

on:
  push:
    branches:
      - main
      - "feature/**"

jobs:
  show-context:
    runs-on: ubuntu-latest
    steps:
      - name: イベント情報を表示
        run: |
          echo "Event name : ${{ github.event_name }}"
          echo "Branch     : ${{ github.ref_name }}"
          echo "Actor      : ${{ github.actor }}"
          echo "SHA        : ${{ github.sha }}"
